# frozen_string_literal: true
source "https://rubygems.org"
gem "tty-prompt"
gem "easy_translate"
gem "rainbow"
gem "rest-client"
gem "json"
gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
